# vim: ft=yaml
language: bash
sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zsh
  - ./tests/integ-tests/install-fish.sh "2.2.0"

install:
  - gem install ronn
  - curl -sL https://git.io/vV4yE | sh
  - echo "PEARL_PACKAGES[test]=\"${PWD}\"" >> ~/.config/pearl/pearl.conf
  - pearl install kobol

script:
  - bash ./tests/integ-tests/integ-tests.sh
  - zsh ./tests/integ-tests/integ-tests.sh
  - fish ./tests/integ-tests/integ-tests.fish
